name: Publish Packages
on:
  push:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build mvn
        run: mvn package

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: AA
          path: target\*
